sudo: required
language: generic

services:
  - docker

before_install:
 - openssl aes-256-cbc -K $encrypted_c6dd56fcd733_key -iv $encrypted_c6dd56fcd733_iv -in ./lab1/.travis/travis.enc -out travis -d
 - cd lab1
 - docker build -t akapust1n/lab1 .
 - cd ..

install:

 
after_success:
  - echo -e "Host *\n\tStrictHostKeyChecking no\nUserKnownHostsFile=/dev/null\n" >> ~/.ssh/config
  - chmod +x lab1/.travis/deploy.sh
  - bash lab1/.travis/deploy.sh
