sudo: required
language: generic

services:
  - docker
#build
before_install:
 - openssl aes-256-cbc -K $encrypted_c6dd56fcd733_key -iv $encrypted_c6dd56fcd733_iv -in ./backend/.travis/travis.enc -out  ./backend/.travis/travis -d
 - sudo curl -L "https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
 - sudo chmod +x /usr/local/bin/docker-compose
 - docker pull akapust1n/rcoi-base:latest
 - cd backend/Dockerfiles
 - docker build . -f Dockerfile -t akapust1n/courcework &&  docker build . -f Dockerfile_comments -t akapust1n/courcework-comments &&  docker build . -f Dockerfile_news -t akapust1n/courcework-news
 - docker build . -f Dockerfile_likehistory -t akapust1n/courcework-likehistory && docker build . -f Dockerfile_users -t akapust1n/courcework-users && docker build . -f Dockerfile_gateway -t akapust1n/courcework-gateway
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 - docker push akapust1n/courcework && docker push akapust1n/courcework-comments &&  docker push akapust1n/courcework-news && docker push akapust1n/courcework-gateway
 - docker push akapust1n/courcework-likehistory && docker push akapust1n/courcework-users


#deploy
after_success:
  - echo -e "Host *\n\tStrictHostKeyChecking no\nUserKnownHostsFile=/dev/null\n" >> ~/.ssh/config
  - cd .. && chmod +x .travis/deploy.sh
  - bash .travis/deploy.sh


