sudo: required
language: generic

services:
  - docker
#build
before_install:
 - openssl aes-256-cbc -K $encrypted_c6dd56fcd733_key -iv $encrypted_c6dd56fcd733_iv -in ./lab2/.travis/travis.enc -out travis -d
 - cd lab2
 - docker build -t akapust1n/lab2 .

#test
install:
