sudo: required
language: generic

services:
  - docker
#build
before_install:
 - openssl aes-256-cbc -K $encrypted_c6dd56fcd733_key -iv $encrypted_c6dd56fcd733_iv -in ./lab2/.travis/travis.enc -out  ./lab2/.travis/travis -d
 - sudo curl -L "https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
 - sudo chmod +x /usr/local/bin/docker-compose
 - docker pull akapust1n/rcoi-base:latest
 - cd lab2/
 - docker build . -f Dockerfile      -t akapust1n/courcework
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 - docker push akapust1n/courcework


#deploy
after_success:
  - echo -e "Host *\n\tStrictHostKeyChecking no\nUserKnownHostsFile=/dev/null\n" >> ~/.ssh/config
  - chmod +x .travis/deploy.sh
  - bash .travis/deploy.sh


