version: '3.1'
services:
  database:
    image: mysql:5.7
    container_name: database.dev
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_USER: root

  lab2:
    image: akapust1n/lab2
    depends_on:
       - database
    volumes:
      - ./3rdpart/wait-for-it.sh:/tmp/wait-for-it.sh
    links:
      - database
    command: bash -c " chmod +x /tmp/wait-for-it.sh && cd /rcoi/lab2/ && bash /tmp/wait-for-it.sh --timeout=60 database:3306 -- bash run_tests.sh" 





